services:

    blog_posts_collection:
        class: MagdKudama\PhaticBlogExtension\Parser\PostsParser
        arguments: ["@service_container"]
    blog_pages_collection:
        class: MagdKudama\PhaticBlogExtension\Parser\PagesParser
        arguments: ["@service_container"]
    blog_homepage_collection:
        class: MagdKudama\PhaticBlogExtension\Parser\HomepageParser
        arguments: ["@service_container"]

    blog_command_generate_site:
        class: MagdKudama\PhaticBlogExtension\Command\GenerateSiteCommand
        tags:
            - { name: phatic.command }

    blog_processor_page:
        class: MagdKudama\PhaticBlogExtension\Processor\PageProcessor
        arguments: ["@service_container"]
        tags:
            - { name: phatic.processor }
    blog_processor_post:
        class: MagdKudama\PhaticBlogExtension\Processor\PostProcessor
        arguments: ["@service_container"]
        tags:
            - { name: phatic.processor }
    blog_processor_homepage:
        class: MagdKudama\PhaticBlogExtension\Processor\HomepageProcessor
        arguments: ["@service_container"]
        tags:
            - { name: phatic.processor }

    blog_view:
        class: MagdKudama\PhaticBlogExtension\View\ViewExtension
        arguments: ["@service_container"]
        tags:
            - { name: phatic.view }

    phatic_blog.permalinks:
        class: MagdKudama\PhaticBlogExtension\Collection\PermalinkCollection

    blog_permalink_date:
        class: MagdKudama\PhaticBlogExtension\Permalink\DatePermalink
        tags:
            - { name: phatic_blog.permalink }
    blog_permalink_prefix:
        class: MagdKudama\PhaticBlogExtension\Permalink\PrefixPermalink
        tags:
            - { name: phatic_blog.permalink }

    blog_permalink_guesser:
        class: MagdKudama\PhaticBlogExtension\Permalink\PermalinkGuesser
        arguments: ["@phatic_blog.permalinks", "%phatic.blog.permalink_options%"]